### ISSUE TITLE
Missing file: pointwise_annotation_training.py

### ISSUE THREAD

**Issue by lauziere** [tommccoy1/raven#1]
Thank you for making the RAVEN code available!

I am trying to follow your steps in 0: Quickstart. However, the repository doesn't contain pointwise_annotation_training.py. 

Could you upload this script? 

Thank you, 

Andrew

**Comment by tommccoy1** [comment]
Thanks so much for pointing this out! It should now be fixed. Please let me know if it works for you.

**Comment by lauziere** [comment]
Thank you - I was able to work through all steps in Quickstart!

**Comment by tommccoy1** [comment]
Great to hear! Then I will close this issue, but please let me know if you run into any other trouble.
